import type { Metadata } from "next";
import "./variables.scss";
import { ServicesProvider } from "@hooks/services.hook";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ServicesProvider>{children}</ServicesProvider>
      </body>
    </html>
  );
}
