export enum CthulhuSkill {
  SAN = 'Santé mentale (SAN)',
  PSY = 'Psychologie',
  PSY_ANA = 'Psychoanalyse',
  ARCHEO = 'Archéologie',
  OCC = 'Occultisme',
  HIST = 'Histoire',
  LANG_EGYPT = 'Langue (hieroglyphes égyptiens)',
  LANG_LATIN = 'Langue (latin)',
  CHARM = 'Charme',
  BS = 'Baratin',
  LIBRARY = 'Bibliothèque',
  FHO = 'Trouver objet caché',
  MED = 'Médecine',
  BIO = 'Sciences (Biologie)',
  NAT = 'Naturalisme',
  URGENT_CARE = 'Premiers soins',
  DEX = 'Dextérité',
  LISTEN = 'Ecouter',
  ESCAPE = 'Esquive',
  MELEE = 'Corps à corps',
  LUCK = 'Chance',
  SCIENCE = 'Sciences',
  CHEM = 'Chimie',
  PHARMA = 'Pharmacie',
  INT = 'Intelligence',
  STRENGTH = 'Force',
  EDU = 'Éducation',
  CON = 'Constitution',
  CTHULHU = 'Mythe de Cthulhu',
  DAMAGE = 'Dégat',
  LOCK_PICK = 'Crochetage',
  PERCEPTION = 'Perception',
  IDEA = 'Idée',
  POWER = 'Pouvoir',
  BULLY = 'Intimidation',
  PERSUASION = 'Persuasion',
  APPEARANCE = 'Apparence',
}

export enum DndSkill {
  ACROBATICS = 'Acrobaties',
  ANIMAL_HANDLING = 'Dressage',
  ARCANA = 'Arcane',
  ATHLETICS = 'Athlétisme',
  DECEPTION = 'Tromperie',
  HISTORY = 'Histoire',
  INSIGHT = 'Intuition',
  INTIMIDATION = 'Intimidation',
  INVESTIGATION = 'Investigation',
  MEDICINE = 'Médecine',
  NATURE = 'Nature',
  PERCEPTION = 'Perception',
  PERFORMANCE = 'Représentation',
  PERSUASION = 'Persuasion',
  RELIGION = 'Religion',
  SLEIGHT_OF_HAND = 'Escamotage',
  STEALTH = 'Discrétion',
  SURVIVAL = 'Survie',  
}

export type Skill = CthulhuSkill | DndSkill;